name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          stale-issue-message: 'This issue has been automatically closed due to inactivity. Please feel free to reopen it if you are still experiencing this problem.'
          days-before-stale: 14
          days-before-close: 7
          stale-issue-label: 'stale'