// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6yZkq-TP5a1f3zT5Z7YB0JqZx_3D0LY',
    appId: '1:401992673899:web:4fd5bfd2931e458f095f2e',
    messagingSenderId: '401992673899',
    projectId: 'programacao-adacb',
    authDomain: 'programacao-adacb.firebaseapp.com',
    storageBucket: 'programacao-adacb.appspot.com',
    measurementId: 'G-ZQ5CTCLHVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwP_JOblY4InCo_LfoiaW-I6RQtArM-fg',
    appId: '1:401992673899:android:eeaf830f6559b8d8095f2e',
    messagingSenderId: '401992673899',
    projectId: 'programacao-adacb',
    storageBucket: 'programacao-adacb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ITp-0QQK5zGj0kK1mg8Txncrtvy5Rmg',
    appId: '1:401992673899:ios:4baf4e40d1e5396a095f2e',
    messagingSenderId: '401992673899',
    projectId: 'programacao-adacb',
    storageBucket: 'programacao-adacb.appspot.com',
    iosBundleId: 'com.programacao.app.RunnerTests',
  );
}
